apiVersion: v1
kind: Service
metadata:
  name: grafana
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http-grafana
  selector:
    name: grafana
  sessionAffinity: None
  type: LoadBalancer
