# https://github.com/grafana/loki/blob/main/production/helm/loki/README.md
loki:
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: azure
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  ingester:
    chunk_encoding: snappy
  querier:
    # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
    max_concurrent: 4
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    retention_period: 672h # 28 days retention
  compactor:
    retention_enabled: true 
    delete_request_store: azure
  storage:
    type: azure
    azure:
      accountName: STORAGE_ACCOUNT_NAME
      accountKey: STORAGE_ACCOUNT_KEY
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler

deploymentMode: SimpleScalable

backend:
  replicas: 2
read:
  replicas: 2
write:
  replicas: 3 # To ensure data durability with replication

gateway:
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"

chunksCache:

resultsCache:

minio:
  enabled: false
