# Complete nginx setup with nginx-prometheus-exporter for Kubernetes
# This includes nginx deployment, nginx-exporter, and all necessary configurations

---
# nginx Service
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - name: nginx
      protocol: TCP
      port: 8080
      targetPort: 8080
    # - name: nginxlog-metrics
    #   protocol: TCP
    #   port: 4040
    #   targetPort: 4040
    - name: nginx-exporter-metrics
      protocol: TCP
      port: 9113
      targetPort: 9113
---
# nginx Deployment with nginxlog-exporter sidecar
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-config
              subPath: nginx.conf
            - mountPath: /var/log/nginx
              name: nginx-logs
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
        # - name: nginxlog-exporter
        #   image: quay.io/martinhelmich/prometheus-nginxlog-exporter
        #   args:
        #     - -config-file=/etc/nginxlog-exporter/config.yaml
        #   ports:
        #     - containerPort: 4040
        #   volumeMounts:
        #     - mountPath: /etc/nginxlog-exporter/config.yaml
        #       name: nginxlog-exporter-config
        #       subPath: config.yaml
        #     - mountPath: /var/log/nginx
        #       name: nginx-logs
        #   resources:
        #     requests:
        #       memory: "64Mi"
        #       cpu: "50m"
        #     limits:
        #       memory: "128Mi"
        #       cpu: "100m"
        #   livenessProbe:
        #     httpGet:
        #       path: /metrics
        #       port: 4040
        #     initialDelaySeconds: 30
        #     periodSeconds: 10
        #     timeoutSeconds: 5
        #     failureThreshold: 3
        #   readinessProbe:
        #     httpGet:
        #       path: /metrics
        #       port: 4040
        #     initialDelaySeconds: 5
        #     periodSeconds: 5
        #     timeoutSeconds: 3
        #     failureThreshold: 3
        - name: nginx-exporter
          image: nginx/nginx-prometheus-exporter:0.11.0
          args:
            - -nginx.scrape-uri=http://localhost:8080/metrics
            - -web.listen-address=:9113
            - -web.telemetry-path=/metrics
            - -nginx.timeout=10s
            - -nginx.retries=3
          ports:
            - containerPort: 9113
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /metrics
              port: 9113
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9113
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        # - name: nginxlog-exporter-config
        #   configMap:
        #     name: nginxlog-exporter-config
        - name: nginx-logs
          emptyDir: {}
---
# nginxlog-exporter ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginxlog-exporter-config
  labels:
    app: nginxlog-exporter
    component: exporter
data:
  config.yaml: |
    listen:
      port: 4040
      metrics_endpoint: "/metrics"
    
    consul:
      enable: false

    namespaces:
      - name: nginx
        source:
          files:
            - /var/log/nginx/access.log
        format: "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$request_time\""
        # labels:
        #   status: status
        #   method: method
        #   path: path
        #   host: host
        #   remote_addr: remote_addr
        #   user_agent: user_agent
        relabel_configs:
          - target_label: request_uri
            from: request
            split: 2
            separator: ' '  
          - source_labels: [status]
            regex: "5.."
            action: replace
            target_label: error_type
            replacement: "server_error"
          - source_labels: [status]
            regex: "4.."
            action: replace
            target_label: error_type
            replacement: "client_error"
          - source_labels: [status]
            regex: "2.."
            action: replace
            target_label: error_type
            replacement: "success"
          - source_labels: [status]
            regex: "3.."
            action: replace
            target_label: error_type
            replacement: "redirect"
        # metrics:
        #   - type: counter
        #     name: nginx_http_requests_total
        #     help: "Total number of HTTP requests"
        #     labels: [status, method, path, host, remote_addr, user_agent, error_type]
        #   - type: histogram
        #     name: nginx_http_request_duration_seconds
        #     help: "HTTP request duration in seconds"
        #     labels: [status, method, path, host]
        #     buckets: [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10]
---
# nginx ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: nginx
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        # include       /etc/nginx/mime.types;
        # default_type  application/octet-stream;

        # log_format  main  '$remote_addr - $remote_user [$time_local] '
        #               '"$request" $status $body_bytes_sent '
        #               '"$http_referer" "$http_user_agent" "$request_time"';

        # access_log  /var/log/nginx/access.log  main;
        # sendfile        on;
        # keepalive_timeout  65;

        upstream api {
            server dice-server:8080;
        }

        server {
            listen 8080;
            server_name localhost;
  
            # Metrics endpoint for nginx-prometheus-exporter
            location /metrics {
                stub_status on;
                access_log off;
                allow 127.0.0.1;
                deny all;
            }

            # Health check endpoint
            location /health {
                access_log off;
                return 200 "healthy\n";
                add_header Content-Type text/plain;
            }

            location / {
                proxy_pass http://api;
                proxy_redirect  off;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Host $host;
            }
        }
    }
