apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - deployment.yaml
  - service.yaml
  - persistentvolumeclaim.yaml

configMapGenerator:
  - name: mimir-config
    files:
    - ./config/mimir.yaml
    options:
      disableNameSuffixHash: true

commonLabels:
  app: mimir
  component: metrics
