apiVersion: v1
kind: Service
metadata:
  labels:
    name: tempo
  name: tempo
spec:
  ports:
    - name: tempo-http
      protocol: TCP
      port: 3200
      targetPort: 3200
    - name: tempo-prom-metrics
      port: 3100
      protocol: TCP
      targetPort: 3100
    - name: tempo-otel-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: tempo-otel-http
      protocol: TCP
      port: 4318
      targetPort: 4318
    - name: tempo-jaeger-thrift-http
      protocol: TCP
      port: 14268
      targetPort: 14268
  selector:
    name: tempo