# yaml-language-server: $schema=https://raw.githubusercontent.com/grafana/k8s-monitoring-helm/refs/heads/main/charts/k8s-monitoring/values.schema.json
---
cluster:
  name: monitoring-cluster

destinations:
  - name: prometheus
    type: prometheus
    url: http://mimir-gateway.monitoring.svc.cluster.local/api/v1/push

  - name: loki
    type: loki
    url: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push
    extraHeaders:
      X-Scope-OrgID: orgId

clusterMetrics:
  enabled: false
  kube-state-metrics:
    podAnnotations: {kubernetes.azure.com/set-kube-service-host-fqdn: "true"}

clusterEvents:
  enabled: false

nodeLogs:
  enabled: false

podLogs:
  enabled: true
  namespaces:
    - prod

collectorCommon:
  alloy:
    controller:
      podAnnotations: {kubernetes.azure.com/set-kube-service-host-fqdn: "true"}

alloy-metrics:
  enabled: false
  alloy:
    extraArgs:
      - --disable-reporting
alloy-singleton:
  enabled: false
  alloy:
    extraArgs:
      - --disable-reporting
alloy-logs:
  enabled: true
  alloy:
    extraArgs:
      - --disable-reporting

# alloy-operator:
#   waitForAlloyRemoval:
